### ISSUE TITLE
Example in Readme

### ISSUE THREAD

**Issue by jefffriesen** [barraponto/neutrino-preset-postcss#1]
I've used postcss + cssnext to import css files into React components. it's such a nice workflow. But I can't get it set up with this neutrino-preset-postcss. 

It looks something like this:
```js
import styles from './component-file.css'
...
render() {
    return (
      <div className={styles.somestyle}>
...
```

Would you mind giving an example of any actual setup? It doesn't have to be what I'm going for above, but if I have something to work with I can probably get it. You mention creating a `postcss.config.js` file which I did but I still can't get it working. 

Thank you.

**Comment by barraponto** [comment]
Can you show your whole setup (or a smaller setup that has the same issue)?
It should *just work* unless React needs some special setup (due to using jsx, maybe).

**Comment by jefffriesen** [comment]
I'm trying to get [CSS Modules](https://github.com/css-modules/postcss-modules) working. I'm translate a PostCSS babel setup into neutrino.js that I've used but didn't set up. Here is the [repo](https://github.com/sapientglobalmarkets/react-mobx-seed) where it works (using Babel/Webpack):

From the readme, it says it uses:
> PostCSS (cssnext + precss + css-modules)

Here is where it is configured:
https://github.com/sapientglobalmarkets/react-mobx-seed/blob/master/package.json
https://github.com/sapientglobalmarkets/react-mobx-seed/blob/master/config/webpack-common.config.js

What this allows is importing a css as a module into a React component:
This [css file](https://github.com/sapientglobalmarkets/react-mobx-seed/blob/master/src/clock/components/clock-page.css) is imported to [this component](https://github.com/sapientglobalmarkets/react-mobx-seed/blob/master/src/clock/components/clock-page.jsx#L4) as a `styles` object and used like:
```js
<div className={styles.clockPage}>
```

In my repo, I've added the `neutrino-preset-postcss` preset:
https://github.com/jefffriesen/neutrino-react-reference/pull/1/files

Originally I was importing `bootstrap.css` globally which was working properly. Now it's not but I'm not clear why: https://github.com/jefffriesen/neutrino-react-reference/blob/postcss/src/index.js#L5-L6

And then the css module import creates an extra `counter.css.json` file. This also doesn't work:
https://github.com/jefffriesen/neutrino-react-reference/blob/postcss/src/counter/counter.jsx#L4-L5

I realize the PostCSS universe is large and it applies to lots of different types of transforms. Mine is a very specific case that you may not use.  I was suggesting adding some examples of how to use the PostCSS preset so people can apply them to their specific case. 

Also I think it's likely people will come to your preset without PostCSS experience (like me - I've never configured it, just used it). Having some concrete examples will help in those cases. 

Thanks

**Comment by barraponto** [comment]
I'm not really using CSS Modules myself, but they seem slightly incompatible with global css frameworks such as Bootstrap. See https://github.com/css-modules/css-modules/issues/113 and https://github.com/css-modules/css-modules/pull/65 and https://github.com/gajus/react-css-modules#global-css

**Comment by jefffriesen** [comment]
@barraponto After playing with this for a while I think CSS Modules works fairly well with the standard neutrino install. (I know PostCSS covers a lot of technology, not just CSS Modules). 

I wrote up how to use them with Neutrino's base configuration here: https://github.com/jefffriesen/neutrino-react-reference#css-modules

They do work with global css frameworks like Bootstrap. In the link above there are examples.

**Comment by barraponto** [comment]
Yeah, css-loader has CSS Modules support on its own and it works quite well. PostCSS enables a lot of extra stuff, but if all you want is CSS Modules, it is not needed.

Plus, I like the "global by default approach". Local by default just makes it harder to work with :P

**Comment by jefffriesen** [comment]
I'm curious about the 'global by default' terminology - what am I using in that example posted?
```
:local :global(.nav > li > a).listItem {
  color: tomato;
}
```

**Comment by barraponto** [comment]
i have no idea. i didn't know you could write `:local` and `:global` in the same line.

**Comment by JawsomeJason** [comment]
Late to the party, but @jefffriesen, given the above, `.listItem` will become locally modularized.  Imagining that it gets scoped as `.abcd`, your selector now becomes:

`.nav > li > a.abcd`

The initial `:local` is required for css-loader to pick this up as a scoped selector.  The wrapped `:global()` states that any selector inside does not get scoped.  Anything after stays in `:local` scope.

**Comment by jefffriesen** [comment]
cool, thanks @thejase
