### ISSUE TITLE
Compatibility with neutrino-preset-react

### ISSUE THREAD

**Issue by sebasmagri** [barraponto/neutrino-preset-postcss#2]
Hi, I've not been able to make this preset work with the React preset. As soon as I enable this preset the build breaks:

```
.../src/index.js
   3:8   error  'React' is defined but never used         no-unused-vars
   5:10  error  'AppContainer' is defined but never used  no-unused-vars
   6:8   error  'App' is defined but never used           no-unused-vars
  12:4   error  'document' is not defined                 no-undef
```

I've tried enabling neutrino-preset-web in several orders without success.

**Comment by barraponto** [comment]
Yeah, `neutrino-preset-react` builds on top of `neutrino-preset-web`, so you only need one of these.
I'll re-think the peer-dependency, but for now, just use `neutrino-preset-react` and `neutrino-preset-postcss` (without `neutrino-preset-web`).
