### ISSUE TITLE
Usage example with extract text

### ISSUE THREAD

**Issue by timkelty** [barraponto/neutrino-preset-postcss#3]
Any idea how to get this working with [ExtractText](https://github.com/webpack-contrib/extract-text-webpack-plugin)?

The furthest I've gotten is getting https://github.com/jaridmargolin/neutrino-middleware-extractstyles to work on its own, like so:

```
  neutrino.use(extractStyles, {
    use: [
      {
        loader: 'css-loader',
        options: {
          sourceMap: true,
        }
      },
      {
        loader: 'postcss-loader',
        options: {
          plugins: [
            cssnext({
              browsers: ['last 2 versions', 'ie 9']
            })
          ]
        }
      },
    ]
  });
```

**Comment by barraponto** [comment]
Heh, it's kind of complicated since that middleware just nukes whatever was previously setup.
I'd say it would be wiser to pick the rules/loaders from previous presets/middlewares and use that to configure Extract Text Plugin.

**Comment by timkelty** [comment]
Agreed. From the discourse in Slack, it looks like one could do this via `styleRule.uses.entries()`.

**Comment by barraponto** [comment]
My experiments led me to https://gist.github.com/barraponto/0f1b28769e824f29c54d827fa9b4b5f9, which i think might work even *without* postcss middlewares. (but it definitely works with this postcss preset)

**Comment by barraponto** [comment]
published https://github.com/barraponto/neutrino-preset-extractstyles
