### ISSUE TITLE
Recomendation: rename the repostitory to 'middleware'

### ISSUE THREAD

**Issue by constgen** [barraponto/neutrino-preset-postcss#4]
I highly recommend to rename this repository from 'neutrino-**preset**-postcss' to 'neutrino-**middleware**-postcss' as it is titled in NPM until any forks are made.

**Comment by barraponto** [comment]
sure thing, @constgen !
btw, there is currently an issue with how this middleware works: it still reads the PostCSS configuration from package.json or config.js, unlike eslint middleware.
I'll fix that and turn this into an actual middleware !

**Comment by barraponto** [comment]
Done!
